// This file is automatically generated and contains assets from arbitrum.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssets: Address[];
  public fxAggregators: Address[];
}

export const USDC_ADDRESS = Address.fromString('0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8');
export const DAI_ADDRESS = Address.fromString('0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1');
export const USDT_ADDRESS = Address.fromString('0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9');
export const TUSD_ADDRESS = Address.fromString('0x4D15a3A2286D883AF0AA1B3f21367843FAc63E07');
export const FRAX_ADDRESS = Address.fromString('0x17FC002b466eEc40DaE837Fc4bE5c67993ddBd6F');
export const MAI_ADDRESS = Address.fromString('0x3F56e0c36d275367b8C502090EDF38289b3dEa0d');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8'), // USDC
    Address.fromString('0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1'), // DAI
    Address.fromString('0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9'), // USDT
    Address.fromString('0x4D15a3A2286D883AF0AA1B3f21367843FAc63E07'), // TUSD
    Address.fromString('0x17FC002b466eEc40DaE837Fc4bE5c67993ddBd6F'), // FRAX
    Address.fromString('0x3F56e0c36d275367b8C502090EDF38289b3dEa0d'), // MAI
  ],
  pricingAssets: [
    Address.fromString('0x82aF49447D8a07e3bd95BD0d56f35241523fBab1'), // WETH
    Address.fromString('0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f'), // WBTC
  ],
  fxAssets: [
  ],
  fxAggregators: [
  ],
};
