// This file is automatically generated and contains assets from bnb.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssets: Address[];
  public fxAggregators: Address[];
}

export const USDC_ADDRESS = Address.fromString('0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d');
export const BUSD_ADDRESS = Address.fromString('0xe9e7cea3dedca5984780bafc599bd69add087d56');
export const USDT_ADDRESS = Address.fromString('0x55d398326f99059ff775485246999027b3197955');
export const TUSD_ADDRESS = Address.fromString('0x14016e85a25aeb13065688cafb43044c2ef86784');
export const FRAX_ADDRESS = Address.fromString('0x90C97F71E18723b0Cf0dfa30ee176Ab653E89F40');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d'), // USDC
    Address.fromString('0xe9e7cea3dedca5984780bafc599bd69add087d56'), // BUSD
    Address.fromString('0x55d398326f99059ff775485246999027b3197955'), // USDT
    Address.fromString('0x14016e85a25aeb13065688cafb43044c2ef86784'), // TUSD
    Address.fromString('0x90C97F71E18723b0Cf0dfa30ee176Ab653E89F40'), // FRAX
  ],
  pricingAssets: [
    Address.fromString('0x2170ed0880ac9a755fd29b2688956bd959f933f8'), // ETH
    Address.fromString('0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c'), // WBNB
    Address.fromString('0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c'), // BTCB
  ],
  fxAssets: [
  ],
  fxAggregators: [
  ],
};
